### ISSUE TITLE
bootloader can not locate ramdisk.img

### ISSUE THREAD

**Issue by jimmy947788** [02047788a/android_device_brcm_rpi4#6]
boot failed... can't entry system....
bootloader can not find ramdisk.img

**Comment by jimmy947788** [comment]
change [config.txt](https://github.com/02047788a/android_device_brcm_rpi4/blob/master/boot/config.txt) & [cmdline.txt](https://github.com/02047788a/android_device_brcm_rpi4/blob/master/boot/cmdline.txt) for raspberry pi4

**Comment by 02047788a** [comment]
> change [config.txt](https://github.com/02047788a/android_device_brcm_rpi4/blob/master/boot/config.txt) & [cmdline.txt](https://github.com/02047788a/android_device_brcm_rpi4/blob/master/boot/cmdline.txt) for raspberry pi4
